FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5087
EXPOSE 5087
EXPOSE 7083

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src/src/Services
COPY ["src/Services/UserService/UserService.csproj", "UserService/"]
COPY ["src/Shared/Shared.BuildingBlocks/Shared.BuildingBlocks.csproj", "../Shared/Shared.BuildingBlocks/"]
RUN dotnet restore "UserService/UserService.csproj"
COPY src/Services/UserService/ UserService/
COPY src/Shared/Shared.BuildingBlocks/ ../Shared/Shared.BuildingBlocks/
WORKDIR "/src/src/Services/UserService"
RUN dotnet build "./UserService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./UserService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UserService.dll"]
